package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("YouTube search test")
    void generatedTest() {
        step("Open 'http://www.youtube.com/'", () -> {
            // todo
        });

        step("Fill search query 'Selenoid'", () -> {
            // todo
        });

        step("Press 'search' button", () -> {
            // todo
        });

        step("Check result list contains video with title that contains 'Иван Крутов'", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'http://www.youtube.com/'", () ->
            open("http://www.youtube.com/"));

        step("Checking that the page title has is 'Bevor Sie zu YouTube weitergehen'", () -> {
            String expectedTitle = "Bevor Sie zu YouTube weitergehen";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}